gravitee-io/gravitee-reporter-api

- src/main/java/io/gravitee/reporter/api/health/HealthStatus.java
> feat(healthcheck): Add a state to the endpoint

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
This closes gravitee-io/issues#113
> feat(analytics): add proxy latency data

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(plan): Implementation of Plans

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(gateway): Manage a request transaction ID from headers

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(gateway): Initial length must be 0

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(gateway): Multi-tenant support

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(log): Request /response analysis

- src/main/java/io/gravitee/reporter/api/AbstractMetrics.java
- src/main/java/io/gravitee/reporter/api/health/HealthStatus.java
- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
- src/main/java/io/gravitee/reporter/api/monitor/Monitor.java
> fix(analytics): Remove gateway information

- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
> feat(log): Add a message settled by the gateway in case of error

- src/main/java/io/gravitee/reporter/api/monitor/JvmInfo.java
> fix(JvmInfo): add getters

- src/main/java/io/gravitee/reporter/api/http/Request.java
- src/main/java/io/gravitee/reporter/api/http/RequestMetrics.java
- src/main/java/io/gravitee/reporter/api/http/Response.java
> feat(logging): Add request / response content for logging feature

- src/main/java/io/gravitee/reporter/api/health/EndpointStatus.java
- src/main/java/io/gravitee/reporter/api/health/Step.java
- src/main/java/io/gravitee/reporter/api/http/Response.java
> feat(healthcheck): Store more information in case of HC fail

- src/main/java/io/gravitee/reporter/api/health/EndpointStatus.java
This closes gravitee-io/issues#1240
> feat: allows to display HC status transitions

- src/main/java/io/gravitee/reporter/api/health/EndpointStatus.java
- src/main/java/io/gravitee/reporter/api/http/Metrics.java
This closes gravitee-io/issues#1312
> feat: display top paths/resources in analytics

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
Closes gravitee-io/issues#1536
> feat(analytics): Add Host HTTP header into analytics

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
This closes gravitee-io/issues#1951
> feat: Add an option to get hits by user agent in analytics dashboard

- src/main/java/io/gravitee/reporter/api/log/Log.java
Closes gravitee-io/issues#1993
> feat(log): Add API ID and timestamp to logs

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
This closes gravitee-io/issues#1948
> feat: Audit on API user from JWT

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
This closes gravitee-io/issues#1997
> feat: Multi analytics dashboards

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
> feat: Add a sparkline graph on subscriptions list

- src/main/java/io/gravitee/reporter/api/monitor/ProcessInfo.java
Closes gravitee-io/issues#2777
> feat(alert): Alerting integration

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
Closes gravitee-io/issues#3191
> fix: Some calls are reported with a negative response time

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
> feat: Support zone in order to group analytics

- src/main/java/io/gravitee/reporter/api/http/Metrics.java
Closes gravitee-io/issues#4769
> feat(assign-metrics): add custom metrics

- src/main/java/io/gravitee/reporter/api/AbstractMetrics.java
Fixes https://github.com/gravitee-io/issues/issues/5097
> Expose timestamp to JSON formatter so it gets included in File Reporter

- .circleci/config.yml
- pom.xml
- src/main/java/io/gravitee/reporter/api/AbstractMetrics.java
Closes gravitee-io/issues#5707
> fix(timestamp): serialize timestamp as simple long

- pom.xml
This reverts partially commit e9af0eed
> Revert "fix(timestamp): serialize timestamp as simple long"

- pom.xml
- src/main/java/io/gravitee/reporter/api/common/Request.java
- src/main/java/io/gravitee/reporter/api/common/Response.java
Closes gravitee-io/issues#6772
> feat(headers): Internal rework and introduce HTTP Headers API

- src/main/java/io/gravitee/reporter/api/jackson/FieldFilterProvider.java
Closes gravitee-io/issues#6911
> fix: avoid jackson field filtering filter when not configured

- src/main/java/io/gravitee/reporter/api/configuration/Rules.java
Closes gravitee-io/issues#6911
> fix: add handy method 'containRules'

- pom.xml
- src/main/java/io/gravitee/reporter/api/AbstractMetrics.java
- src/main/java/io/gravitee/reporter/api/http/Metrics.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-161
---
- use it directly by updating your project with version: `1.24.0-apim-161-manage-mqtt-clients-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.24.0-apim-161-manage-mqtt-clients-SNAPSHOT/gravitee-reporter-api-1.24.0-apim-161-manage-mqtt-clients-SNAPSHOT.zip)
> feat: add client id on metrics

- .circleci/config.yml
- pom.xml
- src/main/java/io/gravitee/reporter/api/AbstractReportable.java
- src/main/java/io/gravitee/reporter/api/Reporter.java
- src/main/java/io/gravitee/reporter/api/common/Request.java
- src/main/java/io/gravitee/reporter/api/health/EndpointStatus.java
- src/main/java/io/gravitee/reporter/api/http/Metrics.java
- src/main/java/io/gravitee/reporter/api/log/Log.java
- src/main/java/io/gravitee/reporter/api/monitor/Monitor.java
- src/main/java/io/gravitee/reporter/api/v4/common/Message.java
- src/main/java/io/gravitee/reporter/api/v4/common/MessageConnectorType.java
- src/main/java/io/gravitee/reporter/api/v4/common/MessageOperation.java
- src/main/java/io/gravitee/reporter/api/v4/log/Log.java
- src/main/java/io/gravitee/reporter/api/v4/log/MessageLog.java
- src/main/java/io/gravitee/reporter/api/v4/metric/MessageMetrics.java
- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
- src/main/java/io/gravitee/reporter/api/v4/metric/NoopMetrics.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
---
- use it directly by updating your project with version: `1.25.0-support-v4-logging-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.25.0-support-v4-logging-SNAPSHOT/gravitee-reporter-api-1.25.0-support-v4-logging-SNAPSHOT.zip)
> APIM-490: Support of metrics/logging on api v4

- .circleci/config.yml
- CHANGELOG.md
- pom.xml
- src/main/java/io/gravitee/reporter/api/AbstractReportable.java
- src/main/java/io/gravitee/reporter/api/Reporter.java
- src/main/java/io/gravitee/reporter/api/common/Request.java
- src/main/java/io/gravitee/reporter/api/health/EndpointStatus.java
- src/main/java/io/gravitee/reporter/api/http/Metrics.java
- src/main/java/io/gravitee/reporter/api/log/Log.java
- src/main/java/io/gravitee/reporter/api/monitor/Monitor.java
- src/main/java/io/gravitee/reporter/api/v4/common/Message.java
- src/main/java/io/gravitee/reporter/api/v4/common/MessageConnectorType.java
- src/main/java/io/gravitee/reporter/api/v4/common/MessageOperation.java
- src/main/java/io/gravitee/reporter/api/v4/log/Log.java
- src/main/java/io/gravitee/reporter/api/v4/log/MessageLog.java
- src/main/java/io/gravitee/reporter/api/v4/metric/MessageMetrics.java
- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
- src/main/java/io/gravitee/reporter/api/v4/metric/NoopMetrics.java
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
> Merge alpha to master

- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-9340
---
- use it directly by updating your project with version: `1.32.3-apim-9340-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.32.3-apim-9340-SNAPSHOT/gravitee-reporter-api-1.32.3-apim-9340-SNAPSHOT.zip)
> fix: fix boolean types

- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
---
- use it directly by updating your project with version: `1.33.0-apim-9340-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.33.0-apim-9340-SNAPSHOT/gravitee-reporter-api-1.33.0-apim-9340-SNAPSHOT.zip)
> feat: add double additional metrics

- src/main/java/io/gravitee/reporter/api/jackson/AdditionalMetricDeserialization.java
- src/main/java/io/gravitee/reporter/api/jackson/HttpHeadersSerializer.java
- src/main/java/io/gravitee/reporter/api/jackson/JacksonUtils.java
- src/main/java/io/gravitee/reporter/api/v4/metric/AdditionalMetric.java
- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
- src/test/java/io/gravitee/reporter/api/jackson/AdditionalMetricDeserializationTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-9761
---
- use it directly by updating your project with version: `1.34.0-apim-9761-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.34.0-apim-9761-SNAPSHOT/gravitee-reporter-api-1.34.0-apim-9761-SNAPSHOT.zip)
> fix: getter control serialization

- src/main/java/io/gravitee/reporter/api/v4/metric/eventnative/EventNativeMetrics.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-10025
Add more metrics, and make some id Nullable
---
- use it directly by updating your project with version: `1.35.0-improv-eventNaticeMetrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.35.0-improv-eventNaticeMetrics-SNAPSHOT/gravitee-reporter-api-1.35.0-improv-eventNaticeMetrics-SNAPSHOT.zip)
> Improv event natice metrics

- pom.xml
- src/main/java/io/gravitee/reporter/api/http/Metrics.java
- src/main/java/io/gravitee/reporter/api/v4/metric/Diagnostic.java
- src/main/java/io/gravitee/reporter/api/v4/metric/Metrics.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-9992
---
- use it directly by updating your project with version: `1.35.0-APIM-9992-detailed-traces-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-api/1.35.0-APIM-9992-detailed-traces-SNAPSHOT/gravitee-reporter-api-1.35.0-APIM-9992-detailed-traces-SNAPSHOT.zip)
> feat: add diagnostic metrics to handle errors
